package com.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class CreditAuth implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_auth.id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_auth.user_id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_auth.credit_id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    private Long creditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_auth.status
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_auth.create_time
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_auth.update_time
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_auth
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_auth.id
     *
     * @return the value of credit_auth.id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_auth.id
     *
     * @param id the value for credit_auth.id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_auth.user_id
     *
     * @return the value of credit_auth.user_id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_auth.user_id
     *
     * @param userId the value for credit_auth.user_id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_auth.credit_id
     *
     * @return the value of credit_auth.credit_id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public Long getCreditId() {
        return creditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_auth.credit_id
     *
     * @param creditId the value for credit_auth.credit_id
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public void setCreditId(Long creditId) {
        this.creditId = creditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_auth.status
     *
     * @return the value of credit_auth.status
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_auth.status
     *
     * @param status the value for credit_auth.status
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_auth.create_time
     *
     * @return the value of credit_auth.create_time
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_auth.create_time
     *
     * @param createTime the value for credit_auth.create_time
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_auth.update_time
     *
     * @return the value of credit_auth.update_time
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_auth.update_time
     *
     * @param updateTime the value for credit_auth.update_time
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}