package com.sys.dao;

import com.sys.entity.Account;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int updateByPrimaryKey(Account record);

    @Select("select * from accounts where account = #{account}")
    Account findByAccount(String account);

    @Select("select email from accounts where account = #{account}")
    String getEmailByAccount(String account);

    @Select("update accounts set email = #{email} where account = #{account}")
    void updEmailByAccount(@Param("email") String email, @Param("account") String account);
}