package com.sys.dao;

import com.sys.entity.CreditOption;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CreditOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_options
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_options
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int insert(CreditOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_options
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int insertSelective(CreditOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_options
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    CreditOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_options
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int updateByPrimaryKeySelective(CreditOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_options
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int updateByPrimaryKey(CreditOption record);

    @Select("select SQL_CALC_FOUND_ROWS * from credit_options limit #{start},10")
    List<CreditOption> findAll(@Param("start") Integer start);

    @Select("select FOUND_ROWS()")
    int getRecordSum();

    List<CreditOption> getOptions(@Param("category") String category,@Param("rank") String rank,@Param("start") Integer start);

    @Select("select distinct category from credit_options")
    List<String> findCategory();

    @Select("select distinct id,category,rank from credit_options where category=#{category}")
    List<CreditOption> getOptionsByCategory(@Param("category") String category);
}