package com.sys.dao;

import com.sys.entity.CreditAuth;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CreditAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_auth
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_auth
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    int insert(CreditAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_auth
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    int insertSelective(CreditAuth CreditAuthrecord);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_auth
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    CreditAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_auth
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    int updateByPrimaryKeySelective(CreditAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_auth
     *
     * @mbggenerated Mon May 07 17:21:35 CST 2018
     */
    int updateByPrimaryKey(CreditAuth record);

    List<CreditAuth> getAuthList(@Param("userId") Long userId, @Param("start") Long start);

    @Select("select FOUND_ROWS()")
    int getRecordSum();

    List<CreditAuth> getAuth(@Param("userId") Long userId, @Param("creditId") Long creditId);

    List<Long> getCreditIds(@Param("userId") Long id);

    @Select("select count(*) from credit_auth where user_id = #{userId} and credit_id = #{creditId} and status = 1")
    Integer getAuthByUserIdAndCreditId(@Param("userId") Integer userId, @Param("creditId") Integer creditId);
}