package com.sys.dao;

import com.sys.entity.WorkOrder;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface WorkOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_orders
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_orders
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int insert(WorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_orders
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int insertSelective(WorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_orders
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    WorkOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_orders
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int updateByPrimaryKeySelective(WorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_orders
     *
     * @mbggenerated Fri Mar 02 14:37:57 CST 2018
     */
    int updateByPrimaryKey(WorkOrder record);

    @Select("select * from work_orders where uuid = #{0}")
    WorkOrder findByUuid(String uuid);

    List<WorkOrder> findByStatus(@Param("userId") Integer userId, @Param("status") Integer status, @Param("start") Integer start);

    List<WorkOrder> findByStatusAndCreditIds(@Param("userId") Integer userId, @Param("status") Integer status, @Param("start") Integer start, @Param("creditIds") List<Long> creditIds);

    @Select("select FOUND_ROWS()")
    int getRows();

    @Select("select count(*) from work_orders where status = 1 and credit_id = #{creditId}")
    int getRowsByPending(@Param("creditId") Integer creditId);

    @Select("select count(*) from work_orders where (status = 2 or status = 3) and auditor_id = #{userId}")
    int getRowsByHandled(@Param("userId") Integer userId);
}